### ISSUE TITLE
access denied to S3 bucket 

### ISSUE THREAD

**Issue by zacronos** [gregburek/heroku-buildpack-postgresql#2]
`curl https://gregburek-buildpack-postgresql.s3.amazonaws.com/cedar/postgresql-9.3.5.tgz` yields the following result:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>B8C2735410219510</RequestId><HostId>IEWj5EzCblZgoo803crRYJNiVjkaU1GEu8RGvV5Sm59BxFR6fJcHdTTLVMT//G8V</HostId></Error>
```

Is there a problem with the S3 bucket?  Or is this buildpack not intended to be used directly?

**Comment by gregburek** [comment]
Checking on this, that file doesn't exist, and in fact the cedar folder is empty. We are on `cedar-14` stack internally and the last time I tried to get `cedar` binaries working, it was a huge rat's nest. I suggest using https://s3.amazonaws.com/gregburek-buildpack-postgresql/postgresql-9.3.4.tgz which should work on cedar. 

Alternately, I recommend going to cedar-14, it is way better and has an official docker image: heroku/cedar:14

**Comment by zacronos** [comment]
Ok, thanks -- I'll see about getting us migrated to cedar-14.
